// Code generated by upstep/codegen; DO NOT EDIT.

package docstore

import (
	"context"

	"gocloud.dev/docstore"

	"github.com/szabba/upstep/planning"
)

type PlanRepository struct {
	coll *docstore.Collection
}

func NewPlanRepository(coll *docstore.Collection) *PlanRepository {
	return &PlanRepository{coll}
}

var _ planning.PlanRepository = new(PlanRepository)

func (repo *PlanRepository) Get(ctx context.Context, id planning.PlanID) (*planning.Plan, error) {
	rawID := id.Value()
	doc := _PlanDoc{ID: rawID}

	err := repo.coll.Get(ctx, &doc)
	if err != nil {
		return nil, translateGetError(err)
	}

	return doc.ToDomain(repo.coll)
}

func (repo *PlanRepository) Save(ctx context.Context, step *planning.Plan) error {
	doc := &_PlanDoc{}
	err := doc.FromDomain(step, repo.coll)
	if err != nil {
		return translateSaveError(err)
	}

	err = repo.coll.Put(ctx, doc)
	return translateSaveError(err)
}
