kind: pipeline
name: default

steps:
- name: build
  image: golang:1.12
  commands:
  - go mod tidy
  - ./check-diff-empty.sh
  - go generate -x ./...
  - ./check-diff-empty.sh
  - go build -v ./...
  - go test -v -cover -coverpkg ./... ./...
